version: "3.7"
services:
  server:
    build: ./
    command: air
    image: soccer-manager
    container_name: server
    ports:
      - 8080:8080
    volumes:
      - code-sync:/soccer-manager/:nocopy
    env_file:
      - config/env/development.env
    environment:
      - PORT=8080
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - db-data-sync:/var/lib/postgresql/data
    env_file:
      - config/env/development.env
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   ports:
  #     - 3005:80
  #   env_file:
  #     - config/env/development.env
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin

volumes:
  # pgadmin:
  code-sync:
    external: true
  db-data-sync: {}
